var data4 = []
data4.push(['loud','0'])
data4.push(['quiet','1'])
data4.push(['very loud','2'])
data4.push(['very loud','2'])
data4.push(['loud','0'])
data4.push(['quiet','1'])
data4.push(['very loud','2'])
data4.push(['very loud','2'])
data4.push(['loud','0'])
data4.push(['quiet','1'])
data4.push(['very loud','2'])
data4.push(['very loud','2'])
data4.push(['very loud','2'])
